// Verbatim Terms text provided by SubTrade Software Ltd.
export const effective = 'Effective Date: July 22, 2025 / Last Updated: July 22, 2025';
export const intro = `Welcome to Subtrade, a construction project management platform developed and operated by Subtrade Software Ltd ("Company", "we", "us", or "our"). By creating an account, accessing, or using Subtrade (the "Platform"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree, do not use the Platform.`;

export const sections = [
{h:'1. Description of Services', b:[
`Subtrade Software Ltd provides a comprehensive Software-as-a-Service (SaaS) platform designed for the construction industry. Our Services include, but are not limited to, functionalities for Leads/Bids, Estimating, Proposals, Time Management, Geofence, Field Management, Safety Management, Resources Management, Schedule Management, Communication Management, Document Management, and Photo Gallery.`,
`In addition to these core functionalities, we may offer supplementary support services such as installation assistance, maintenance, and bug fixing, as further detailed in your specific service agreement.`]},
{h:'2. Eligibility and Use of the Platform', b:[
`2.1 Eligibility. You must be at least 18 years old and have the legal authority to enter into these Terms.`,
`2.2 Permitted Use. You may use Subtrade only as intended: to manage construction projects, tasks, drawings, time tracking and team collaboration.`,
`2.3 Prohibited Uses. You agree not to: reverse-engineer, copy, or resell any part of the platform; upload malicious code, illegal content, or anything that violates laws or third-party rights; abuse platform resources or attempt unauthorized access to any systems or data.`]},
{h:'3. Accounts and Access', b:[
`You are responsible for: keeping your credentials confidential; ensuring that your account information is accurate and up-to-date; all activity that occurs under your account.`,
`We may suspend or terminate accounts that violate these Terms.`]},
{h:'4. License to Use the Software', b:[
`Subject to your compliance with these Terms, Subtrade Software Ltd grants you a limited, non-exclusive, non-transferable, revocable license to access and use the SaaS Services solely for your internal business operations as permitted by the SaaS Licence.`]},
{h:'5. Intellectual Property Rights', b:[
`Subtrade Software Ltd retains all ownership rights, title, and interest in and to the Software, its underlying code, design, content, and any data provided by Subtrade Software Ltd. This includes all intellectual property rights (IPR) associated with the SaaS Services and Software.`,
`You are expressly prohibited from attempting to modify, decompile, reverse engineer, or distribute Subtrade Software Ltd's intellectual property without our explicit prior written consent.`,
`Regarding new intellectual property that may arise through the use of the Software: You retain ownership of your input data. However, Subtrade Software Ltd retains ownership of the underlying algorithms, methodologies, general insights derived from aggregated or anonymized data, and any improvements or modifications to the Software resulting from your interaction or use. This ensures a fair and transparent ownership structure for newly arising IPR while protecting Subtrade Software Ltd's core intelligence.`]},
{h:'6. Files and Content', b:[
`You may upload files (drawings, photos, documents) related to your construction projects. You retain ownership of your content, but you grant us a license to store, process, and display it to provide the services.`,
`We do not claim ownership over your data. However, we may temporarily store it on services such as AWS S3, EFS, Redis, and others.`]},
{h:'7. Data Ownership, Usage, and Security', b:[
`7.1 Data Ownership. The Customer retains full control and ownership over their own data ("Data") supplied to or processed by the Services.`,
`7.2 Data License. You grant to Subtrade Software Ltd a limited, non-exclusive, royalty-free license to copy, transmit, store, back-up, or otherwise access, use, or make reference to any Intellectual Property Rights in the Data for the following specific, defined purposes: to supply the Services, including enabling you, your personnel, and any authorized users to access and use the Services; to perform analysis for the purposes of predictive safety analytics, industry guideline production, and other construction safety-related uses, provided such Data is re-identified or anonymized; for diagnostic purposes; to test, enhance, and otherwise modify the Services, whether requested by you or not; to develop other Services; as reasonably required for the performance of Subtrade Software Ltd's obligations under this Agreement.`,
`7.3 Customer Warranties. You represent and warrant that: any and all Data supplied by you or otherwise accessed by Subtrade Software Ltd through the provision of the Services is your sole and exclusive property, or you have secured all necessary authorizations and rights to use the Data as applicable; your Data does not breach any relevant laws, regulations, or codes; your Data does not infringe the Intellectual Property Rights of any third party; you will comply with all applicable laws and regulations in the jurisdiction where you access and publish content using the SaaS Services; to the extent that the Data contains personal data, you have obtained the necessary consents in order to transfer or permit access to this Data in accordance with applicable privacy and data protection laws.`,
`7.4 Data Collection and Management. The Services collect various types of construction-specific data, including but not limited to material quantities, labor hours, equipment usage, safety incidents, and quality inspections. This data may be collected via digital forms, sensors, IoT devices, drones, BIM integration, and wearables. Data management relies on cloud-based storage solutions, centralized ERP systems, and automated backups.`,
`7.5 Data Integrity and Responsibility. You acknowledge and agree that: any collation, conversion, and analysis of Data performed as part of the Services, whether by the Services or otherwise, is likely to be subject to human input and machine errors, omissions, delays, and losses, including but not limited to any loss of Data. Subtrade Software Ltd is not liable for any such errors, omissions, delays, or losses. You are responsible for adopting reasonable measures to limit the impact of such loss or error. Subtrade Software Ltd may relocate the Data to another jurisdiction; in each case, Subtrade Software Ltd will give you 15 Business Days' notice and use all reasonable endeavors to minimize the effect of such change on your access and use of the Services. Subtrade Software Ltd is not responsible for any corruption or loss of any Data if such corruption or loss is due to an act or omission by you, your personnel, your related bodies corporate, or any authorized users. Subtrade Software Ltd is not responsible for the integrity or existence of any Data on your environment, network, or any device controlled by you or your personnel.`,
`7.6 Data Protection and Confidentiality. Subtrade Software Ltd is committed to safeguarding customer data. We implement technical and organizational measures to protect data and comply with applicable data protection laws, including but not limited to Canada's Personal Information Protection and Electronic Documents Act (PIPEDA), relevant US state privacy laws such as the California Consumer Privacy Act (CCPA) as amended by the California Privacy Rights Act (CPRA), and international regulations like the UK GDPR. Further details on our data handling practices, including information on cross-border data transfers, are provided in our Privacy Policy.`]},
{h:'8. Offline Use', b:[
`Subtrade includes offline features in its mobile app. Local data (e.g., project files, tasks, photos) is stored on your device and synchronized when connectivity is restored.`]},
{h:'9. System Availability', b:[
`We aim for high uptime but cannot guarantee uninterrupted access. Maintenance, updates, or AWS outages may affect availability.`]},
{h:'10. Financial Terms', b:[
`You agree to pay Subtrade Software Ltd: the Fee as specified in your service agreement; and any other amount payable to Subtrade Software Ltd under this Agreement.`,
`Payment terms, including frequency of payments and consequences of late payments, will be clearly outlined in your specific service agreement or invoice.`]},
{h:'11. Termination', b:[
`You may delete your account at any time. We may suspend or delete accounts that: violate these Terms; pose a security risk; are inactive for extended periods.`,
`Upon termination of this Agreement, you will immediately: cease and desist from any use of the Services; return to Subtrade Software Ltd all property, including Confidential Information and Intellectual Property, in your possession that belongs to Subtrade Software Ltd; pay the Fees for all Services completed up to the date of termination.`,
`All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.`]},
{h:'12. Limitation of Liability', b:[
`12.1 General Limitations. To the fullest extent permitted by law, Subtrade and Subtrade Software Ltd ("Company") disclaim all warranties, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement.`,
`12.2 Exclusion of Damages. In no event shall the Company be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to: loss of profits, revenue, or business opportunities; loss of data or project information; construction delays or project cost overruns; loss of use, savings, or goodwill; business interruption costs.`,
`12.3 Cap on Direct Damages. The Company's total liability for any claims arising from or related to the Platform shall not exceed the greater of: $100 USD; or the total fees paid by you to the Company in the 12 months preceding the incident.`,
`12.4 Platform-Specific Limitations. The Company is specifically not liable for: Data Processing Errors (inaccuracies in OCR text recognition, file conversions, Change Order, Purchase Orders, and RFIs data processing); Location Services (GPS inaccuracies, geofencing errors, or location-based feature malfunctions); Third-Party Dependencies (outages or failures of AWS, internet connectivity, or other third-party services); Offline Synchronization (data conflicts, sync failures, or information loss during offline-to-online transitions); File Integrity (corruption, loss, or modification of uploaded drawings, photos, or documents); Communication Features (failed notifications, delayed messages, or missed alerts).`,
`12.5 User Responsibility. You acknowledge that: construction projects involve inherent risks and tight deadlines; you should maintain independent backups of critical project data; the Platform is a tool to assist, not replace, professional judgment and industry best practices; you remain solely responsible for project management decisions and compliance with safety regulations.`,
`12.6 Exceptions. These limitations do not apply to: Company's gross negligence or willful misconduct; violations of applicable data protection laws where liability cannot be legally limited; claims for which limitation would be prohibited by law in your jurisdiction.`,
`12.7 Time Limitation. Any claims against the Company must be brought within one (1) year of when the cause of action arose, or such claims shall be forever barred.`,
`12.8 Acknowledgment. You acknowledge that these limitations are reasonable given the nature of the service and the fees charged, and that the Company would not provide the Platform without these limitations.`]},
{h:'13. Changes to These Terms', b:[
`We may update these Terms occasionally. Continued use after changes indicates your acceptance of the revised Terms. The "Last Updated" date at the top of these Terms will be revised to reflect any changes.`]},
{h:'14. General Provisions', b:[
`14.1 Governing Law. These Terms shall be governed and construed in accordance with the laws of the Province of Alberta and the federal laws of Canada applicable therein, without regard to its conflict of law provisions.`,
`14.2 Entire Agreement. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.`,
`14.3 Severability. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect.`,
`14.4 Waiver. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and Subtrade Software Ltd's failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.`]},
{h:'15. App Store Specific Terms', b:[
`The following terms apply when you access the Subtrade application through the Apple App Store or Google Play Store.`,
`15.1 Terms Applicable to Apple App Store Users. Acknowledgement: You and Subtrade Software Ltd acknowledge that this End-User License Agreement (EULA) is concluded between you and Subtrade Software Ltd only, and not with Apple, Inc. ("Apple"). Subtrade Software Ltd, not Apple, is solely responsible for the Licensed Application and the content thereof. This EULA does not provide for usage rules for Licensed Applications that are in conflict with the Apple Media Services Terms and Conditions as of the Effective Date (which you acknowledge you have had the opportunity to review).`,
`Scope of License: The license granted to you for the Licensed Application is limited to a non-transferable license to use the Licensed Application on any Apple-branded Products that you own or control and as permitted by the Usage Rules set forth in the Apple Media Services Terms and Conditions. This license does not allow you to use the Licensed Application on any Apple Device that you do not own or control, and except as provided in the Usage Rules, you may not distribute or make the Licensed Application available over a network where it could be used by multiple devices at the same time. You may not rent, lease, lend, sell, transfer, redistribute, or sublicense the Licensed Application.`,
`Maintenance and Support: Subtrade Software Ltd is solely responsible for providing any maintenance and support services with respect to the Licensed Application, as specified in this EULA or as required under applicable law. You and Subtrade Software Ltd acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Licensed Application.`,
`Warranty: Subtrade Software Ltd is solely responsible for any product warranties, whether express or implied by law, to the extent not effectively disclaimed. In the event of any failure of the Licensed Application to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the Licensed Application to you. To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the Licensed Application, and any other claims, losses, liabilities, damages, costs, or expenses attributable to any failure to conform to any warranty will be Subtrade Software Ltd's sole responsibility.`,
`Product Claims: You and Subtrade Software Ltd acknowledge that Subtrade Software Ltd, not Apple, is responsible for addressing any claims by you or any third party relating to the Licensed Application or your possession and/or use of that Licensed Application, including, but not limited to: (i) product liability claims; (ii) any claim that the Licensed Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection, privacy, or similar legislation. This EULA does not limit Subtrade Software Ltd's liability to you beyond what is permitted by applicable law.`,
`Intellectual Property Rights: You and Subtrade Software Ltd acknowledge that, in the event of any third-party claim that the Licensed Application or your possession and use of that Licensed Application infringes that third party's intellectual property rights, Subtrade Software Ltd, not Apple, will be solely responsible for the investigation, defense, settlement, and discharge of any such intellectual property infringement claim.`,
`Legal Compliance: You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.`,
`Third-Party Terms of Agreement: You must comply with applicable third-party terms of agreement when using the Licensed Application (e.g., your wireless data service agreement).`,
`Apple as Third-Party Beneficiary: You and Subtrade Software Ltd acknowledge and agree that Apple, and Apple's subsidiaries, are third-party beneficiaries of this EULA, and that, upon your acceptance of the terms and conditions of this EULA, Apple will have the right (and will be deemed to have accepted the right) to enforce this EULA against you as a third-party beneficiary thereof.`,
`Consent to Use of Technical Data: You agree that Subtrade Software Ltd may collect and use technical data and related information, including but not limited to technical information about your device, system and application software, and peripherals, that is gathered periodically to facilitate the provision of software updates, product support, and other services related to the Licensed Application.`,
`15.2 Terms Applicable to Google Play Store Users. No Mandatory EULA: While Google Play does not strictly require an End-User License Agreement (EULA), we provide these Terms to protect our intellectual property and limit our liability to users of our app.`,
`Updates: By using the Service, you agree to install updates to the Service that Subtrade Software Ltd introduces from time to time. Applications originating from Subtrade Software Ltd may communicate with our servers from time to time to check for available updates to the Applications and to the functionality of the Service. By using the Service, you agree to such automatically requested and received updates.`,
`Security Features: You may not attempt, nor assist, authorize, or encourage others, to circumvent, disable, or defeat any of the security features or components, such as digital rights management software or encryption, that protect, obfuscate, or otherwise restrict access to the Service. If you violate any security feature, you may incur civil or criminal liability.`,
`Proprietary Notices: You may not remove any watermarks, labels, or other legal or proprietary notices included in any Application, and you may not attempt to modify any Applications obtained through the Service, including any modification for the purpose of disguising or changing any indications of the ownership or source of an Application.`,
`Geographic Restrictions: You agree to only distribute a given Application to End Users that are physically located in a country which Subtrade Software Ltd has approved as a country of distribution.`]},
{h:'16. SMS/Text Messaging Terms', b:[
`Business Identity: Subtrade Software Ltd ("SubTrade") offers SMS and text message notifications to users who have opted in. These messages may include appointment reminders, service updates, promotional offers, and other communications related to SubTrade's construction management platform.`,
`Opt-Out & Support: You can cancel the SMS service at any time. Just text "STOP" to the phone number from which you received the message. After you send the SMS message "STOP" to us, we will send you an SMS message to confirm that you have been unsubscribed. After this, you will no longer receive SMS messages from us. If you want to join again, just sign up as you did the first time and we will start sending SMS messages to you again. If you are experiencing issues with the messaging program you can reply with the keyword HELP for more assistance, or you can get help directly at support@subtradesoftware.com.`,
`Carrier Liability: Carriers are not liable for delayed or undelivered messages.`,
`Message Frequency: As always, message and data rates may apply for any messages sent to you from us and to us from you. Message frequency may vary. If you have any questions about your text plan or data plan, it is best to contact your wireless provider.`,
`Privacy: If you have any questions regarding privacy, please read our privacy policy at subtradesoftware.com/privacy-policy.`]},
{h:'Contact Us', b:[
`If you have any questions regarding this agreement, please contact us at support@subtradesoftware.com.`]},
];
