// US construction retainage by state.
//
// publicPct / privatePct:
//   number  = statutory ceiling, in percent
//   0       = retainage is prohibited (New Mexico)
//   null    = NO statutory ceiling. The contract controls. This is NOT zero and
//             it is NOT "unknown" — it is the states where a sub has the least
//             protection, so the UI must say so in words rather than render a
//             blank or a 0%.
//
// publicDays / privateDays: the normal statutory release clock, in days, or
// null where the statute sets no deadline. These genuinely differ between
// public and private work in about a dozen states, which is why they are two
// fields rather than one.
//
// Nothing here is legal advice. Retainage law is moving quickly right now —
// California, New York, Mississippi, Washington, Ohio, Iowa, Illinois and
// Kentucky have all changed inside the last three years, and several of those
// changes are not yet reflected in the popular secondary sources.

export const STATES = [
  {
    code: 'AL',
    name: 'Alabama',
    publicPct: 5,
    privatePct: 10,
    publicDays: 35,
    privateDays: 60,
    statute: 'Ala. Code §39-2-12 / §8-29-3',
    reduction: 'Further withholding stops once the work is 50% complete.',
    note: '',
  },
  {
    code: 'AK',
    name: 'Alaska',
    publicPct: null,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: 'AS §36.90.210',
    reduction: '',
    note: 'No statutory ceiling on either side. A prime must pay a sub within 8 working days of being paid.',
  },
  {
    code: 'AZ',
    name: 'Arizona',
    publicPct: 10,
    privatePct: null,
    publicDays: 60,
    privateDays: null,
    statute: 'A.R.S. §34-221(C)',
    reduction: 'At 50% complete, half the retainage is released and the rate drops to 5%.',
    note: 'Private work is not capped by statute.',
  },
  {
    code: 'AR',
    name: 'Arkansas',
    publicPct: 5,
    privatePct: null,
    publicDays: 30,
    privateDays: null,
    statute: 'Ark. Code §22-9-604',
    reduction: 'Further withholding stops at 50% complete.',
    note: '',
  },
  {
    code: 'CA',
    name: 'California',
    publicPct: 5,
    privatePct: 5,
    publicDays: 60,
    privateDays: 45,
    statute: 'Pub. Cont. Code §7201 / Civ. Code §8811',
    reduction: '',
    note: 'The 5% private cap is new. SB 61 applies it to contracts entered into on or after January 1, 2026.',
  },
  {
    code: 'CO',
    name: 'Colorado',
    publicPct: 5,
    privatePct: 5,
    publicDays: 60,
    privateDays: null,
    statute: 'C.R.S. §24-91-103 / §38-46-103',
    reduction: '',
    note: 'The private cap came in with HB21-1167 and applies above a $150,000 contract threshold.',
  },
  {
    code: 'CT',
    name: 'Connecticut',
    publicPct: 7.5,
    privatePct: 5,
    publicDays: null,
    privateDays: 30,
    statute: 'Conn. Gen. Stat. §49-41b / §42-158k',
    reduction: 'State projects step 7.5% down to 5% at 50% complete.',
    note: 'CTDOT withholds 2.5% and municipalities 5%. Private retainage must be held in escrow.',
  },
  {
    code: 'DE',
    name: 'Delaware',
    publicPct: 5,
    privatePct: null,
    publicDays: 60,
    privateDays: null,
    statute: '29 Del. C. §6962(d)(5)',
    reduction: '',
    note: 'Released in two stages, 60% then 40%. Private work is not capped.',
  },
  {
    code: 'DC',
    name: 'District of Columbia',
    publicPct: 10,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: 'D.C. Code §2-203.01',
    reduction: '',
    note: 'A reduction at 50% complete is at the Mayor’s discretion, not automatic. Private work is not capped.',
  },
  {
    code: 'FL',
    name: 'Florida',
    publicPct: 5,
    privatePct: null,
    publicDays: 28,
    privateDays: null,
    statute: 'Fla. Stat. §255.078 / §218.735',
    reduction: '',
    note: 'The old 10%-until-50% rule was repealed in 2020. Release is punch-list driven and runs 20 business days.',
  },
  {
    code: 'GA',
    name: 'Georgia',
    publicPct: 5,
    privatePct: null,
    publicDays: 30,
    privateDays: null,
    statute: 'O.C.G.A. §13-10-80',
    reduction: '',
    note: 'Flat 5% since July 1, 2022, with a $250,000 threshold from July 1, 2025. GDOT projects are excluded.',
  },
  {
    code: 'HI',
    name: 'Hawaii',
    publicPct: 5,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: 'HRS §103-32.1',
    reduction: 'Further withholding stops at 50% complete.',
    note: 'A prime must pay subs within 10 days of being paid.',
  },
  {
    code: 'ID',
    name: 'Idaho',
    publicPct: 5,
    privatePct: 5,
    publicDays: 30,
    privateDays: 35,
    statute: 'Idaho Code §54-1926(3) / §29-115',
    reduction: '',
    note: '',
  },
  {
    code: 'IL',
    name: 'Illinois',
    publicPct: 10,
    privatePct: 10,
    publicDays: null,
    privateDays: null,
    statute: '815 ILCS 603/20; 30 ILCS 550/1',
    reduction: 'Drops to 5% at 50% complete.',
    note: 'State agencies are not covered until June 1, 2027. IDOT and the Tollway are excluded.',
  },
  {
    code: 'IN',
    name: 'Indiana',
    publicPct: 6,
    privatePct: null,
    publicDays: 61,
    privateDays: null,
    statute: 'Ind. Code §36-1-12-14',
    reduction: 'The owner elects either 6% until 50% complete, or a flat 3% throughout.',
    note: 'Applies to contracts over $200,000. Private work is not capped.',
  },
  {
    code: 'IA',
    name: 'Iowa',
    publicPct: 3,
    privatePct: null,
    publicDays: 30,
    privateDays: null,
    statute: 'Iowa Code ch. 573',
    reduction: '',
    note: 'Cut from 5% to 3% effective July 1, 2025. Most secondary sources still say 5%.',
  },
  {
    code: 'KS',
    name: 'Kansas',
    publicPct: 5,
    privatePct: 5,
    publicDays: 30,
    privateDays: 30,
    statute: 'K.S.A. §16-1904 / §16-1804',
    reduction: '',
    note: '5% is the default; 10% is the hard ceiling where there are documented performance concerns.',
  },
  {
    code: 'KY',
    name: 'Kentucky',
    publicPct: 10,
    privatePct: 10,
    publicDays: 30,
    privateDays: 30,
    statute: 'KRS §371.410',
    reduction: 'Drops to 5% of the total contract at 50% complete.',
    note: 'Escrow is required on contracts of $2 million or more as of June 27, 2025.',
  },
  {
    code: 'LA',
    name: 'Louisiana',
    publicPct: 10,
    privatePct: null,
    publicDays: 45,
    privateDays: null,
    statute: 'La. R.S. §38:2248',
    reduction: 'Tiered by contract size — 10% under $500,000, 5% at or above it.',
    note: 'Private work is not capped.',
  },
  {
    code: 'ME',
    name: 'Maine',
    publicPct: 5,
    privatePct: null,
    publicDays: null,
    privateDays: 30,
    statute: '5 M.R.S. §1746',
    reduction: '',
    note: 'The 5% cap binds state contracts only. Municipal and private work are not capped.',
  },
  {
    code: 'MD',
    name: 'Maryland',
    publicPct: 5,
    privatePct: 5,
    publicDays: 120,
    privateDays: 90,
    statute: 'Md. SFP §17-110 / Real Prop. §9-304',
    reduction: '',
    note: 'Both caps are conditional on 100% performance and payment security. Contracts under $100,000 are exempt.',
  },
  {
    code: 'MA',
    name: 'Massachusetts',
    publicPct: 5,
    privatePct: 5,
    publicDays: 65,
    privateDays: 90,
    statute: 'M.G.L. c.30 §39K/§39G; c.149 §29F',
    reduction: '',
    note: 'The private cap applies to contracts of $3 million or more. It is 5% of each payment.',
  },
  {
    code: 'MI',
    name: 'Michigan',
    publicPct: 10,
    privatePct: null,
    publicDays: 30,
    privateDays: null,
    statute: 'MCL 125.1563',
    reduction: '10% until 50% complete, then nothing further is withheld — a freeze, not a step-down to 5%.',
    note: 'Private work is not capped.',
  },
  {
    code: 'MN',
    name: 'Minnesota',
    publicPct: 5,
    privatePct: 5,
    publicDays: 60,
    privateDays: 60,
    statute: 'Minn. Stat. §337.10 subd. 4 / §15.72',
    reduction: '',
    note: 'Withholding for disputed work is capped at 250% of the disputed value. Warranty withholding is banned outright.',
  },
  {
    code: 'MS',
    name: 'Mississippi',
    publicPct: 5,
    privatePct: 5,
    publicDays: 45,
    privateDays: 60,
    statute: 'Miss. Code §31-5-33 / §87-9-3',
    reduction: '',
    note: 'The private cap is new — SB 2762, effective July 1, 2024. Most secondary sources still show private as uncapped.',
  },
  {
    code: 'MO',
    name: 'Missouri',
    publicPct: 5,
    privatePct: 10,
    publicDays: 30,
    privateDays: 30,
    statute: 'Mo. Rev. Stat. §8.960 / §436.303',
    reduction: '',
    note: 'Private retainage is capped at 10%. The public statute was renumbered from §34.057 in 2022.',
  },
  {
    code: 'MT',
    name: 'Montana',
    publicPct: 5,
    privatePct: 5,
    publicDays: 30,
    privateDays: null,
    statute: 'Mont. Code §18-2-316 / §28-2-2110',
    reduction: '',
    note: 'A hard 5% on both sides, with no step-down at 50%.',
  },
  {
    code: 'NE',
    name: 'Nebraska',
    publicPct: 10,
    privatePct: 10,
    publicDays: 45,
    privateDays: 45,
    statute: 'Neb. Rev. Stat. §45-1204',
    reduction: 'Drops to 5% once your own scope is 50% complete.',
    note: 'State of Nebraska contracts are excluded from the statute.',
  },
  {
    code: 'NV',
    name: 'Nevada',
    publicPct: 5,
    privatePct: 5,
    publicDays: 30,
    privateDays: 30,
    statute: 'NRS 338.515 / 624.609',
    reduction: '',
    note: 'The old 10% private rate was repealed effective January 1, 2016.',
  },
  {
    code: 'NH',
    name: 'New Hampshire',
    publicPct: null,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: 'No retainage statute',
    reduction: '',
    note: 'No cap, no release deadline, and no prompt payment act. Your contract is the only protection you have.',
  },
  {
    code: 'NJ',
    name: 'New Jersey',
    publicPct: 2,
    privatePct: null,
    publicDays: 45,
    privateDays: null,
    statute: 'N.J.S.A. 40A:11-16.3',
    reduction: '',
    note: 'The lowest public cap in the country. School projects are a 5% exception. Private work is not capped.',
  },
  {
    code: 'NM',
    name: 'New Mexico',
    publicPct: 0,
    privatePct: 0,
    publicDays: 21,
    privateDays: 21,
    statute: 'N.M. Stat. §57-28-5',
    reduction: '',
    note: 'Retainage is prohibited outright. Only state road projects (§67-3-48) may withhold, and then at 5%.',
  },
  {
    code: 'NY',
    name: 'New York',
    publicPct: 5,
    privatePct: 5,
    publicDays: 30,
    privateDays: 30,
    statute: 'State Fin. §139-f; GBL §756-c, §757',
    reduction: '',
    note: 'S5655, effective December 19, 2025, voids private contract clauses requiring more than 5%. Private rules apply at $150,000 and up.',
  },
  {
    code: 'NC',
    name: 'North Carolina',
    publicPct: 5,
    privatePct: null,
    publicDays: 60,
    privateDays: null,
    statute: 'N.C.G.S. §143-134.1',
    reduction: 'Further withholding stops at 50% complete.',
    note: 'Retainage is prohibited on public contracts under $100,000. Early-finishing trades are held at 0.5%.',
  },
  {
    code: 'ND',
    name: 'North Dakota',
    publicPct: 10,
    privatePct: 10,
    publicDays: null,
    privateDays: null,
    statute: 'N.D.C.C. §48-01.2-13 / §43-07-23',
    reduction: 'Further withholding stops at 50% complete.',
    note: '',
  },
  {
    code: 'OH',
    name: 'Ohio',
    publicPct: 4,
    privatePct: null,
    publicDays: 30,
    privateDays: null,
    statute: 'ORC §153.12',
    reduction: '',
    note: 'H.B. 96, effective September 30, 2025, replaced the old 8%-until-50% regime with a flat 4%. Both regimes are live depending on when the contract was signed.',
  },
  {
    code: 'OK',
    name: 'Oklahoma',
    publicPct: 5,
    privatePct: null,
    publicDays: 21,
    privateDays: null,
    statute: '61 Okla. Stat. §113.1, §226',
    reduction: 'Drops to 2.5% at 50% complete.',
    note: 'ODOT and Turnpike Authority projects take no retainage. Private work is not capped.',
  },
  {
    code: 'OR',
    name: 'Oregon',
    publicPct: 5,
    privatePct: 5,
    publicDays: 30,
    privateDays: 30,
    statute: 'ORS 279C.570 / 701.420',
    reduction: '',
    note: 'HB 4006 (2024) removed the escrow mandate and added a bond option.',
  },
  {
    code: 'PA',
    name: 'Pennsylvania',
    publicPct: 10,
    privatePct: null,
    publicDays: 45,
    privateDays: null,
    statute: '62 Pa. C.S. §3921',
    reduction: 'At 50% complete the rate drops to 5% and half the retainage is returned.',
    note: 'The Department of General Services uses 6% stepping down to 3%. Private work is not capped.',
  },
  {
    code: 'RI',
    name: 'Rhode Island',
    publicPct: 5,
    privatePct: 5,
    publicDays: 90,
    privateDays: 90,
    statute: 'R.I. Gen. Laws §37-12-10.1',
    reduction: '',
    note: 'Release runs 30 days after a 60-day waiting period. Private coverage is inferential rather than express.',
  },
  {
    code: 'SC',
    name: 'South Carolina',
    publicPct: 3.5,
    privatePct: null,
    publicDays: 10,
    privateDays: null,
    statute: 'S.C. Code §11-35-3030(4)',
    reduction: '',
    note: 'Binds state projects; the position for counties and municipalities is unsettled. Primes pay subs within 10 days.',
  },
  {
    code: 'SD',
    name: 'South Dakota',
    publicPct: null,
    privatePct: null,
    publicDays: 30,
    privateDays: null,
    statute: 'S.D.C.L. §5-18B-11, §9-42-12',
    reduction: '',
    note: '§7-25-10 sets minimum retainage on county buildings (12% / 5% / 2.5%) — that is a floor, not a ceiling.',
  },
  {
    code: 'TN',
    name: 'Tennessee',
    publicPct: 5,
    privatePct: 5,
    publicDays: 90,
    privateDays: 90,
    statute: 'Tenn. Code §66-34-103',
    reduction: '',
    note: 'The cap cannot be waived. Escrow is required on contracts of $500,000 or more, with a $300/day penalty.',
  },
  {
    code: 'TX',
    name: 'Texas',
    publicPct: 10,
    privatePct: null,
    publicDays: 30,
    privateDays: null,
    statute: 'Gov’t Code §2252.032 / Prop. Code §53.101',
    reduction: 'Public retainage tiers down by size — 10% under $5 million, 5% at or above it.',
    note: 'Private retainage is not capped. Property Code §53.101 makes an owner reserve a 10% lien fund; that is a duty owed to claimants, not a limit on what can be withheld from you.',
  },
  {
    code: 'UT',
    name: 'Utah',
    publicPct: 5,
    privatePct: 5,
    publicDays: 45,
    privateDays: 45,
    statute: 'Utah Code §13-8-5',
    reduction: '',
    note: 'One statute governs both sides: 5% of each payment and 5% of the total. It cannot be waived.',
  },
  {
    code: 'VT',
    name: 'Vermont',
    publicPct: null,
    privatePct: null,
    publicDays: 30,
    privateDays: 30,
    statute: '9 V.S.A. §4005',
    reduction: '',
    note: 'No cap on either side. The prompt payment act sets the clock but not the percentage.',
  },
  {
    code: 'VA',
    name: 'Virginia',
    publicPct: 5,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: 'Va. Code §2.2-4333',
    reduction: '',
    note: 'Private work is expressly carved out of the prompt payment reforms and is not capped.',
  },
  {
    code: 'WA',
    name: 'Washington',
    publicPct: 5,
    privatePct: 5,
    publicDays: 60,
    privateDays: null,
    statute: 'RCW 60.28.011 / ch. 60.30',
    reduction: '',
    note: 'The private 5% cap is new — ESSB 5528, effective July 23, 2023. Residential buildings under 12 units are exempt.',
  },
  {
    code: 'WV',
    name: 'West Virginia',
    publicPct: null,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: 'No retainage statute',
    reduction: '',
    note: 'The only state in the country with no retainage statute at all, public or private.',
  },
  {
    code: 'WI',
    name: 'Wisconsin',
    publicPct: 5,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: 'Wis. Stat. §66.0901(9)(b)',
    reduction: 'Further withholding stops at 50% complete.',
    note: 'Can reach 10% on certified unsatisfactory progress. WisDOT is excluded. Private work is not capped.',
  },
  {
    code: 'WY',
    name: 'Wyoming',
    publicPct: 5,
    privatePct: null,
    publicDays: 41,
    privateDays: null,
    statute: 'Wyo. Stat. §16-6-702(b)',
    reduction: '',
    note: '2020 HB 52 set a flat 5% and deleted the old 50% rule. Release runs 41 days after published notice.',
  },
  {
    code: 'XX',
    name: 'Other / set my own',
    publicPct: null,
    privatePct: null,
    publicDays: null,
    privateDays: null,
    statute: null,
    reduction: '',
    note: '',
  },
];

// Display helper shared by the calculator and the rates table, so that a null
// ceiling never renders as 0% or as an empty cell.
export function capLabel(v) {
  if (v === null || v === undefined) return 'No statutory cap';
  if (v === 0) return 'Prohibited';
  return `${v}%`;
}

export function releaseLabel(s) {
  const a = s.publicDays;
  const b = s.privateDays;
  if (a == null && b == null) return 'No statutory deadline';
  if (a === b) return `${a} days`;
  return `${a == null ? '—' : a} / ${b == null ? '—' : b} days`;
}
