// Each tutorial lives at /tutorials/<slug> matching the old WordPress URLs.
// videoId: the YouTube video ID (the part after v= or youtu.be/).
// Fill in each videoId before launch; pages render a link to the channel until then.
// pdf (optional): path to a PDF guide in /public/guides/. Adds a download button
// on the tutorial page and a "PDF guide" tag on the card.
// published (optional): YYYY-MM-DD the video went up on YouTube (used for video search results).
// series (optional): { name, part, of } links the parts with Previous / Next buttons.
export const tutorials = [
  {
    slug: 'how-to-create-a-project-subtrade-software',
    title: 'Project dashboard and templates',
    blurb: 'Run every job from one screen and start each new one from a template.',
    videoId: 'OUYpHYuhJ2w',
    published: '2026-09-27',
    pdf: '/guides/subtrade-project-dashboard-guide.pdf',
    content: {
      lead: `Every job you're running sits on one Projects page. This walkthrough shows how to read a project card, create a new job in a couple of minutes, and build templates so every job of the same type starts set up the way you work.`,
      learnTitle: `In this tutorial you'll learn how to:`,
      learn: [
        `Switch between active and archived jobs and search any project by name`,
        `Read a project card: progress, tasks, team, dates and status`,
        `Create a project with customer, crew, job site address and schedule`,
        `Build a template per job type with tasks, priority, start and due days`,
        `Load default team members, drawing folders and forms into a template`,
        `Set the statuses for tasks, RFIs, change orders and POs`,
      ],
      body: [
        `Leave the project code blank and SubTrade numbers the job for you. Archive a job when it wraps up and your active list stays clean.`,
        `Want it on paper? Download the PDF guide below and hand it to your PMs and supervisors.`,
      ],
    },
  },
  {
    slug: 'forms-dashboard-subtrade-software',
    title: 'Forms, Part 1: The forms dashboard',
    blurb: 'Every form, folder and submission in one place. Start of the 4-part forms series.',
    videoId: '23v4AXu-E6k',
    published: '2026-09-27',
    pdf: '/guides/subtrade-forms-guide-part-1.pdf',
    series: { name: 'Forms', part: 1, of: 4 },
    content: {
      lead: `Forms live in two places in SubTrade. The Forms page is your master library, where you build every form, file it in folders and see every submission. Each project has its own Forms tab where you bring in only the forms that job needs.`,
      learnTitle: `In this part you'll learn how to:`,
      learn: [
        `Tell the main Forms page apart from a project's Forms tab`,
        `Read the counters: total, active, deployed, with approval, public access and undeployed`,
        `Use Quick Insights to see where your forms stand`,
        `Create folders like Safety, Quality Control and Material Count Sheets`,
        `Search the forms list, edit a form, move it to a folder, duplicate or delete it`,
      ],
      body: [
        `Update a form in the library once and every project using it gets the same version.`,
        `Want it on paper? Download the PDF guide below, then carry on to Part 2.`,
      ],
    },
  },
  {
    slug: 'build-a-form-subtrade-software',
    title: 'Forms, Part 2: Build a form',
    blurb: 'Drag in the fields, preview it on a phone and add automations that email or open tasks on their own.',
    videoId: 'aYBgrEDRFV0',
    published: '2026-09-27',
    pdf: '/guides/subtrade-forms-guide-part-2.pdf',
    series: { name: 'Forms', part: 2, of: 4 },
    content: {
      lead: `Build anything from a quick sign-in sheet to a full hazard assessment with photos, signatures and automations. Same builder, as simple or as detailed as the job calls for.`,
      learnTitle: `In this part you'll learn how to:`,
      learn: [
        `Find your way around the builder: elements, your form and settings`,
        `Use field elements like checklists, photo capture, signatures and yes/no`,
        `Add static info the crew can't change: images, PDFs, location, weather and attendees`,
        `Drag, drop and preview the form on a phone or tablet`,
        `Set form settings like public access, approvals and signatures`,
        `Add conditional logic and automations that send emails or create tasks`,
      ],
      body: [
        `Example: a worker ticks "Working alone" and the PM gets an email right away with the form attached.`,
        `Want it on paper? Download the PDF guide below, then carry on to Part 3.`,
      ],
    },
  },
  {
    slug: 'forms-in-projects-subtrade-software',
    title: 'Forms, Part 3: Forms in your projects',
    blurb: 'Bring the right forms into each job, post a QR code on site and track every submission.',
    videoId: 'BJI2jNuzVT0',
    published: '2026-09-27',
    pdf: '/guides/subtrade-forms-guide-part-3.pdf',
    series: { name: 'Forms', part: 3, of: 4 },
    content: {
      lead: `Once your forms are built, bring them into your projects. Every project has its own Forms page, so each job only gets the forms it needs, and every submission on that job is tracked in one spot.`,
      learnTitle: `In this part you'll learn how to:`,
      learn: [
        `Open a project's Forms page`,
        `Add forms from your library to the job`,
        `Share a form's QR code so anyone on site can fill it in`,
        `See project submissions, trends and approvals`,
        `Check team activity: who's submitting and who isn't`,
        `Search and filter every submission on the job`,
      ],
      body: [
        `The project view shows that job only. For every submission across the company, use View Submissions on the main Forms page.`,
        `Want it on paper? Download the PDF guide below, then carry on to Part 4.`,
      ],
    },
  },
  {
    slug: 'review-form-submissions-subtrade-software',
    title: 'Forms, Part 4: Review submissions',
    blurb: 'Find any submission, see it the way the crew filled it in and download a branded PDF.',
    videoId: 'pEi5Vdas92E',
    published: '2026-09-27',
    pdf: '/guides/subtrade-forms-guide-part-4.pdf',
    series: { name: 'Forms', part: 4, of: 4 },
    content: {
      lead: `Review submissions company-wide from View Submissions on the main Forms page, or one job at a time from that project's Forms page. Open any submission exactly the way the crew filled it in, and download a clean PDF with your logo on it.`,
      learnTitle: `In this part you'll learn how to:`,
      learn: [
        `Filter submissions by date range, user, project or form`,
        `Read the submissions activity list`,
        `Open a submission and see every answer, location and signature`,
        `Download a branded PDF of any submission`,
      ],
      body: [
        `The PDF carries your company logo, name and address, ready for a safety audit or to send straight to the GC.`,
        `That wraps up the forms series. Download the PDF guide below.`,
      ],
    },
  },
  {
    slug: 'bid-manager-pipeline-subtrade-software',
    title: 'Bid Manager, Part 1: Your bid pipeline',
    blurb: 'Every tender on one board, with your pipeline value, win rate and a New Tender button.',
    videoId: 'JbtD3J8YEuI',
    published: '2026-09-27',
    pdf: '/guides/subtrade-bid-manager-guide-part-1.pdf',
    series: { name: 'Bid Manager', part: 1, of: 3 },
    content: {
      lead: `Bid Manager is new in SubTrade. Every tender you're invited to lives on one board, from the day it lands in your inbox to the day it's awarded or lost.`,
      learnTitle: `In this part you'll learn how to:`,
      learn: [
        `Read the board: Incoming Tender, Estimating, Sent, Follow-up, Awarded, Lost and Non-tendered`,
        `Track open pipeline, awarded value, win rate and active bids`,
        `Search by tender, quote number or client, and filter by estimator`,
        `Switch to list view and add a New Tender`,
      ],
      body: [
        `Each card shows the project, the company, the bid value and the due date. When a closing date gets close, the card counts down, and missed ones are flagged Overdue.`,
        `Download the PDF guide below, then carry on to Part 2.`,
      ],
    },
  },
  {
    slug: 'bid-manager-inside-a-tender-subtrade-software',
    title: 'Bid Manager, Part 2: Inside a tender',
    blurb: 'The map, the dates, the GC contact, your scope and the drawings, all on one tender.',
    videoId: 'DsHGG-49omo',
    published: '2026-09-27',
    pdf: '/guides/subtrade-bid-manager-guide-part-2.pdf',
    series: { name: 'Bid Manager', part: 2, of: 3 },
    content: {
      lead: `Press any card on the Bid Manager board and the tender opens. Everything about that bid is in one place, and when the GC makes the call you mark it awarded or lost.`,
      learnTitle: `In this part you'll learn how to:`,
      learn: [
        `Use the tender header to edit details and mark a bid awarded or lost`,
        `Find the site on the map and open directions for the job walk`,
        `Track invited, job walk, RFI, due, start and finish dates`,
        `Keep the GC contact, scope of work and drawings with the bid`,
      ],
      body: [
        `The Drawings tab holds every tender document and addendum as it arrived, sorted into folders like architectural, structural and addendums.`,
        `Download the PDF guide below, then carry on to Part 3.`,
      ],
    },
  },
  {
    slug: 'bid-manager-proposals-vendors-follow-ups-subtrade-software',
    title: 'Bid Manager, Part 3: Proposals, vendors and follow-ups',
    blurb: 'Build and revise proposals, get vendor pricing without the email chase, and auto-chase before the due date.',
    videoId: 'Aqhdu2CVox0',
    published: '2026-09-27',
    pdf: '/guides/subtrade-bid-manager-guide-part-3.pdf',
    series: { name: 'Bid Manager', part: 3, of: 3 },
    content: {
      lead: `Price the job without leaving the tender. Proposals live on the Estimating tab, vendor pricing requests go out from the Vendors tab, and the Follow-ups tab keeps everything moving until the bid is in.`,
      learnTitle: `In this part you'll learn how to:`,
      learn: [
        `Build proposals with their own quote numbers and keep every revision`,
        `Invite a vendor to price the drawings, no account needed`,
        `See exactly what your vendor receives`,
        `Turn on auto-chase and work your open follow-ups`,
      ],
      body: [
        `Takeoff and estimating are coming very soon. For now, the Estimating tab is where your proposals live.`,
        `That wraps up the Bid Manager series. Download the PDF guide below.`,
      ],
    },
  },
  {
    slug: 'progress-billing-subtrade-software',
    title: 'Progress billing: SOV, claims and holdback',
    blurb: 'Set up a job for billing, claim by percent or amount, bring in change orders and track every dollar of holdback.',
    videoId: 'uQTLHVyawno',
    published: '2026-09-29',
    pdf: '/guides/subtrade-progress-billing-guide.pdf',
    content: {
      lead: `Build your schedule of values once, put in a claim every month in minutes, bring in approved change orders, and always know what you've billed, what you've been paid and what's still held back.`,
      learnTitle: `In this video you'll learn how to:`,
      learn: [
        `Fill in the contract value, number and date in your project settings`,
        `Start billing a project from an SOV template, with holdback and warranty holdback`,
        `Put in a claim by percent complete or by dollar amount`,
        `Bill approved change orders, credits, back charges and allowances`,
        `Read the amount due, the project reconciliation and the holdback tracker`,
      ],
      body: [
        `Your schedule of values has to add up to the contract amount. Once a claim is accepted, approve and lock it so the numbers can't change.`,
        `Download the PDF guide below for whoever does your billing.`,
      ],
    },
  },
  {
    slug: 'project-reports-subtrade-software',
    title: 'Project reports: share progress with your client',
    blurb: 'Build a client report from the job and send it as a one-time PDF or a live link locked with a PIN.',
    videoId: 'Z2eVjuY1ehU',
    published: '2026-10-03',
    pdf: '/guides/subtrade-project-reports-guide.pdf',
    content: {
      lead: `Show your client the work without building a report by hand. Pick what goes in, then email it once as a PDF or share a live link they can check anytime.`,
      learnTitle: `In this video you'll learn how to:`,
      learn: [
        `Find every report for a job on the project's Reports page`,
        `Choose a one-time PDF by email or a live activity link`,
        `Add an SOV summary with % complete, claimed to date and remaining`,
        `Pick photos by album, tasks by status, forms and daily reports`,
        `Lock a live link with a 4-digit PIN and an expiry date`,
        `See exactly what your client sees when they open it`,
      ],
      body: [
        `Make as many reports as you want, one per client or one per scope. Drag the grip dots on any section to change the order it shows in the report.`,
        `Download the PDF guide below for your PMs and office.`,
      ],
    },
  },
  {
    slug: 'setup-new-employees-fast-in-subtrade-software',
    title: 'Set up new employees fast',
    blurb: 'Add crew members and get them clocking in the same day.',
    videoId: '9k-B3G5IFKc',
    published: '2025-09-29',
  },
  {
    slug: 'workflow-efficiency-with-employee-time-sheets',
    title: 'Employee time sheets workflow',
    blurb: 'Review, correct and approve crew hours without the Friday detective work.',
    videoId: 'yadJ0PqzO5k',
    published: '2026-09-26',
    pdf: '/guides/subtrade-timesheet-guide.pdf',
    content: {
      lead: `Every hour your crew clocks lands on one Timesheet page. This walkthrough shows how to review those hours, approve them before payroll, and check who was actually on site, without chasing anyone down on Friday.`,
      learnTitle: `In this tutorial you'll learn how to:`,
      learn: [
        `Filter hours by pay period, project or employee, and export them to CSV`,
        `Read the totals: gross hours, breaks, payable hours and labour cost`,
        `Approve or reject time before it reaches payroll`,
        `Fix or stop a running timer when someone forgets to clock out`,
        `Check each worker's pay period totals and every entry behind them`,
        `See whether a punch was on site or off site, with the exact pin on a map`,
      ],
      body: [
        `Pending Approvals is a company setting. Turn it on in Company Settings when you want a supervisor to sign off on hours before they count toward payroll.`,
        `Want it on paper? Download the PDF guide below and hand it to your supervisors.`,
      ],
    },
  },
  {
    slug: 'time-tracking-approval-and-the-time-splitting',
    title: 'Time tracking approval and time splitting',
    blurb: 'Approve time and split hours across jobs and cost codes.',
    videoId: 'VYoNEFi7GqU',
    published: '2026-02-08',
  },
  {
    slug: 'manage-change-orders-subtrade-software',
    title: 'Manage change orders',
    blurb: 'Create, price, send and track change orders from the field.',
    videoId: 'gSl3P6ZYrlM',
    published: '2026-01-07',
  },
  {
    slug: 'purchase-orders-approval',
    title: 'Purchase orders and approval',
    blurb: 'Create POs from the field and run them through approval.',
    videoId: 'TOlQrawWAaE',
    published: '2026-04-14',
    content: {
      lead: `Learn how to set up and manage the full purchase order approval workflow in SubTrade — from configuring company settings to collecting signatures and sending approved POs.`,
      learnTitle: `In this tutorial you'll learn how to:`,
      learn: [
        `Enable purchase order approvals in your company settings`,
        `Assign an approver to your PO workflow`,
        `Create a purchase order inside a project`,
        `Request approval and manage signature requests`,
        `Confirm signatures and send approved purchase orders`,
      ],
      body: [
        `SubTrade is built specifically for trade subcontractors — drywall, electrical, plumbing, HVAC, roofing, and more. Stop chasing paper approvals and run your jobs with a system that actually fits how you work in the field.`,
      ],
    },
  },
  {
    slug: 'subtrade-tutorial-auto-naming-construction-drawings',
    title: 'Auto-naming construction drawings',
    blurb: 'Upload a drawing set and let SubTrade name and organize the sheets.',
    videoId: '6Sl9PQ5N92k',
    published: '2025-09-29',
  },
  {
    slug: 'crew-scheduling-subtrade-software',
    title: 'Crew scheduling',
    blurb: 'Book your crew for the week, repeat shifts and catch double-bookings.',
    videoId: 'MxCJSzEnXL4',
    published: '2026-09-26',
    pdf: '/guides/subtrade-scheduling-guide.pdf',
    content: {
      lead: `The Schedule shows your whole crew for the week: who's working, what hours, and on which job. This walkthrough shows how to book shifts fast and keep anyone from getting double-booked.`,
      learnTitle: `In this tutorial you'll learn how to:`,
      learn: [
        `Read the week at a glance: total scheduled hours, the week scroller and daily or weekly view`,
        `Filter the schedule by employee or by project`,
        `Book one worker or a whole crew in a single shift`,
        `Repeat a shift across several days and skip weekends automatically`,
        `Use the Morning, Afternoon, All Day and Night presets, or set custom and overnight hours`,
        `Assign the project, task and notes, and let SubTrade skip any shift that clashes`,
      ],
      body: [
        `Book next week's shifts before Friday and your crew sees where they're going on their phone.`,
        `Want it on paper? Download the PDF guide below and hand it to your supervisors.`,
      ],
    },
  },
  {
    slug: 'scheduling-feature-workflow-construction-drawings-upload',
    title: 'Scheduling workflow and drawings upload',
    blurb: 'Schedule crews and attach the right drawings to the right job.',
    videoId: '5prhlCrc0BU',
    published: '2026-02-08',
  },
  {
    slug: 'custom-notifications',
    title: 'Custom notifications',
    blurb: 'Choose what your crew and office get notified about, and when.',
    videoId: 'P7cCwB33_QQ',
    published: '2025-12-08',
  },
  {
    slug: 'manage-time-tracking-and-approvals',
    title: 'Manage time tracking and approvals',
    blurb: 'Run the full time tracking workflow from clock-in to approval.',
    videoId: '0R906kMBrCc',
    published: '2026-04-05',
  },
  {
    slug: 'creating-and-submitting-a-daily-report',
    title: 'Create and submit a daily report',
    blurb: 'File a detailed daily report with weather, manpower and photos.',
    videoId: 'YiYaNBgRVRY',
    published: '2026-04-12',
    content: {
      lead: `Learn how to create and submit a daily report in SubTrade Software, step by step. This tutorial walks you through the complete daily reporting workflow, from logging general notes and site conditions to tracking manpower, equipment, materials, and activity progress.`,
    },
  },
  {
    slug: 'introducing-field-operations',
    title: 'Introducing Field Operations',
    blurb: 'A tour of the Field Operations dashboard: live crews, alerts and sites.',
    videoId: '8eddsG-K56Y',
    published: '2026-04-13',
    content: {
      lead: `We just dropped something big. Introducing Field Operations: one screen that shows you everything happening across all your active jobs, right now.`,
      learnTitle: `What Field Operations gives you:`,
      learn: [
        `Priority alerts ranked by what needs action first`,
        `Live job site map — see who's on site, who's late, who didn't show up`,
        `Crew status per site in real time`,
        `Change orders, timesheets and signatures waiting on you`,
        `Full 7-day manpower view across every project`,
      ],
      body: [
        `No more jumping between jobs to figure out what's on fire. It's all in one place, and it's live today for every SubTrade account, at no extra cost.`,
      ],
    },
  },
];
